/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppScamDetectorRouteImport } from './routes/_app.scam-detector'
import { Route as AppReportFraudRouteImport } from './routes/_app.report-fraud'
import { Route as AppGraphIntelligenceRouteImport } from './routes/_app.graph-intelligence'
import { Route as AppGeoIntelligenceRouteImport } from './routes/_app.geo-intelligence'
import { Route as AppFraudShieldRouteImport } from './routes/_app.fraud-shield'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCurrencyDetectionRouteImport } from './routes/_app.currency-detection'
import { Route as AppCrimeIntelligenceRouteImport } from './routes/_app.crime-intelligence'
import { Route as AppAdminRouteImport } from './routes/_app.admin'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppScamDetectorRoute = AppScamDetectorRouteImport.update({
  id: '/scam-detector',
  path: '/scam-detector',
  getParentRoute: () => AppRoute,
} as any)
const AppReportFraudRoute = AppReportFraudRouteImport.update({
  id: '/report-fraud',
  path: '/report-fraud',
  getParentRoute: () => AppRoute,
} as any)
const AppGraphIntelligenceRoute = AppGraphIntelligenceRouteImport.update({
  id: '/graph-intelligence',
  path: '/graph-intelligence',
  getParentRoute: () => AppRoute,
} as any)
const AppGeoIntelligenceRoute = AppGeoIntelligenceRouteImport.update({
  id: '/geo-intelligence',
  path: '/geo-intelligence',
  getParentRoute: () => AppRoute,
} as any)
const AppFraudShieldRoute = AppFraudShieldRouteImport.update({
  id: '/fraud-shield',
  path: '/fraud-shield',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCurrencyDetectionRoute = AppCurrencyDetectionRouteImport.update({
  id: '/currency-detection',
  path: '/currency-detection',
  getParentRoute: () => AppRoute,
} as any)
const AppCrimeIntelligenceRoute = AppCrimeIntelligenceRouteImport.update({
  id: '/crime-intelligence',
  path: '/crime-intelligence',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin': typeof AppAdminRoute
  '/crime-intelligence': typeof AppCrimeIntelligenceRoute
  '/currency-detection': typeof AppCurrencyDetectionRoute
  '/dashboard': typeof AppDashboardRoute
  '/fraud-shield': typeof AppFraudShieldRoute
  '/geo-intelligence': typeof AppGeoIntelligenceRoute
  '/graph-intelligence': typeof AppGraphIntelligenceRoute
  '/report-fraud': typeof AppReportFraudRoute
  '/scam-detector': typeof AppScamDetectorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin': typeof AppAdminRoute
  '/crime-intelligence': typeof AppCrimeIntelligenceRoute
  '/currency-detection': typeof AppCurrencyDetectionRoute
  '/dashboard': typeof AppDashboardRoute
  '/fraud-shield': typeof AppFraudShieldRoute
  '/geo-intelligence': typeof AppGeoIntelligenceRoute
  '/graph-intelligence': typeof AppGraphIntelligenceRoute
  '/report-fraud': typeof AppReportFraudRoute
  '/scam-detector': typeof AppScamDetectorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/crime-intelligence': typeof AppCrimeIntelligenceRoute
  '/_app/currency-detection': typeof AppCurrencyDetectionRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/fraud-shield': typeof AppFraudShieldRoute
  '/_app/geo-intelligence': typeof AppGeoIntelligenceRoute
  '/_app/graph-intelligence': typeof AppGraphIntelligenceRoute
  '/_app/report-fraud': typeof AppReportFraudRoute
  '/_app/scam-detector': typeof AppScamDetectorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/admin'
    | '/crime-intelligence'
    | '/currency-detection'
    | '/dashboard'
    | '/fraud-shield'
    | '/geo-intelligence'
    | '/graph-intelligence'
    | '/report-fraud'
    | '/scam-detector'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/admin'
    | '/crime-intelligence'
    | '/currency-detection'
    | '/dashboard'
    | '/fraud-shield'
    | '/geo-intelligence'
    | '/graph-intelligence'
    | '/report-fraud'
    | '/scam-detector'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/register'
    | '/_app/admin'
    | '/_app/crime-intelligence'
    | '/_app/currency-detection'
    | '/_app/dashboard'
    | '/_app/fraud-shield'
    | '/_app/geo-intelligence'
    | '/_app/graph-intelligence'
    | '/_app/report-fraud'
    | '/_app/scam-detector'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/scam-detector': {
      id: '/_app/scam-detector'
      path: '/scam-detector'
      fullPath: '/scam-detector'
      preLoaderRoute: typeof AppScamDetectorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/report-fraud': {
      id: '/_app/report-fraud'
      path: '/report-fraud'
      fullPath: '/report-fraud'
      preLoaderRoute: typeof AppReportFraudRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/graph-intelligence': {
      id: '/_app/graph-intelligence'
      path: '/graph-intelligence'
      fullPath: '/graph-intelligence'
      preLoaderRoute: typeof AppGraphIntelligenceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/geo-intelligence': {
      id: '/_app/geo-intelligence'
      path: '/geo-intelligence'
      fullPath: '/geo-intelligence'
      preLoaderRoute: typeof AppGeoIntelligenceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fraud-shield': {
      id: '/_app/fraud-shield'
      path: '/fraud-shield'
      fullPath: '/fraud-shield'
      preLoaderRoute: typeof AppFraudShieldRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/currency-detection': {
      id: '/_app/currency-detection'
      path: '/currency-detection'
      fullPath: '/currency-detection'
      preLoaderRoute: typeof AppCurrencyDetectionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/crime-intelligence': {
      id: '/_app/crime-intelligence'
      path: '/crime-intelligence'
      fullPath: '/crime-intelligence'
      preLoaderRoute: typeof AppCrimeIntelligenceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppCrimeIntelligenceRoute: typeof AppCrimeIntelligenceRoute
  AppCurrencyDetectionRoute: typeof AppCurrencyDetectionRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFraudShieldRoute: typeof AppFraudShieldRoute
  AppGeoIntelligenceRoute: typeof AppGeoIntelligenceRoute
  AppGraphIntelligenceRoute: typeof AppGraphIntelligenceRoute
  AppReportFraudRoute: typeof AppReportFraudRoute
  AppScamDetectorRoute: typeof AppScamDetectorRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppCrimeIntelligenceRoute: AppCrimeIntelligenceRoute,
  AppCurrencyDetectionRoute: AppCurrencyDetectionRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFraudShieldRoute: AppFraudShieldRoute,
  AppGeoIntelligenceRoute: AppGeoIntelligenceRoute,
  AppGraphIntelligenceRoute: AppGraphIntelligenceRoute,
  AppReportFraudRoute: AppReportFraudRoute,
  AppScamDetectorRoute: AppScamDetectorRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
